### PR TITLE
Add sources page content, switch listbox to combobox, add groups to selects

### LINKED ISSUE #20: "Sources" page content
Split from #15

Say where sources came from. Defer to CancerInFocus's sources page rather than duplicating data.

### LINKED ISSUE #25: Change multi-select to combobox?
Particularly the overlays/markers/locations multi-select might end up with a lot of options. Right now, it does have "type-ahead", where typing some characters while the box is focused jumps to the next option that starts with those characters. Operating systems like windows and linux do this too in their file explorer windows. But I think most people don't know about that functionality, and it also doesn't support searching for characters at any position in the text; it has to start with the characters.

Convert to this component instead:
https://headlessui.com/react/combobox

### LINKED ISSUE #26: Need human-readable labels for CU cancer center marker data
- wwc-15-jun-2021
- ccsp-15-jun-2021
- title-x-15-jun-2021
- chc-15-jun-2021
- rhc-15-jun-2021
- ihs-15-jun-2021
- genetic-coun-15-jun-2021
- all-treatment-15-jun-2021
- med-onc-15-jun-2021
- surg-onc-15-jun-2021
- rad-onc-15-jun-2021
- ped-onc-15-jun-2021
- trials-15-jun-2021
- all-support-services-15-jun-2021
- pt-rehab-15-jun-2021
- nutrition-15-jun-2021
- support-grp-15-jun-2021
- support-coun-15-jun-2021
- survivorship-15-jun-2021
- lodging-15-jun-2021
- financial-coun-15-jun-2021
- palliative-15-jun-2021
- hospice-15-jun-2021
- cancer-ed-29-jul-221
- accessories-aids-29-jul-21
- programs-events-29-jul-21
- fitness-29-jul-21
- home-family-care-29-jul-21
- transportation-29-jul-21
- pediatric-29-jul-21
- radiology

Also split this up into 3 to 5 (?) high level categories and multi-selects.

### LINKED ISSUE #37: Unselecting locations does not remove them from the map

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #37 
Closes #20 
Closes #26 (splitting locations into groups in the dropdown)
Closes #25 

- update packages
- fix map layer remove bug
- refactor select component to be a combobox allowing search and groupings
- add map of location groupings
- paste in and format sources page content

### CODE REVIEW

**Comment by vincerubinetti** [comment]
This can be reviewed, aside from `location-groups.json` not being real yet.

**Review by falquaddoomi — APPROVED** [review]
Neat! I like how you styled the group sections in the combobox, and that both the groups and items are searchable. I glanced through the code and didn't see anything that stood out. I tried it out in the Netlify preview, too, and things worked as I'd expect. Nice work!

One minor thing: I think it's fine for this PR, but going forward it would help me to see comments when you make changes to the components' interfaces. For example, you now expose a ref in AppButton, but I wasn't clear why that change was made. If it's not worth it to add comments (like, if it's really an internal detail that people don't need explained) or you otherwise don't think it'll be useful to future readers, no worries; I just thought I'd bring it up in case it was an oversight.

**Comment by falquaddoomi** [comment]
Another minor thing, and not really related to this PR, is that the map's height appears to be sized to the viewport, but since there's a header on the page the bottom of the map ends up being clipped unless you scroll down. I noticed this when selecting locations, that the legend was a little truncated without scrolling. Again, not a big deal, but perhaps we could compute the height of the map panel (the map itself plus the button controls under it, e.g. the "Fit" button) to not include the header, or we could do something a little weird like snap the viewport to the top of the map section so that the entire working area is in view if they scroll down a little...just random ideas, and again, not a big deal.

**Comment by vincerubinetti** [comment]
In this case, the appbutton ref was an oversight yeah. I was trying to solve [this issue](https://github.com/tailwindlabs/headlessui/discussions/1236) and exposing the ref was one part of that, but ultimately I couldn't do it without hacking the library, and I forgot to take the ref back out too.

In general though, it looks like for the components at least I wasn't giving too many comments, in this project.

**Comment by vincerubinetti** [comment]
I will look into the viewport thing while we're waiting on the location groupings. It will probably require js, I'm not sure there's a CSS only way to do that.

**Comment by falquaddoomi** [comment]
> I will look into the viewport thing while we're waiting on the location groupings. It will probably require js, I'm not sure there's a CSS only way to do that.

Your most recent commit seems to have fixed it for me (in Chrome on OS X). IMHO this is a nicer user experience on first view of the page; kudos for getting it done so quick!

**Pull request merged**
