### PR TITLE
redesign frontend

### PR DESCRIPTION
**Pull request by vincerubinetti**

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Some things to note:

- Might want to think about making terms more consistent, e.g. variables, measures, values, levels, etc. Right now, my definitions are:
    - Measures = The schema/definition/hierarchy that become selections.
    - Facet = One "level" of the measures, i.e. "geographic level" ("level" for short), "variable category" ("category" for short), "variable" ("variable" for short).
    - Values = The per-feature data for the selected facets. A map of FIPS (or whatevever feature id) to a numerical value that gets plotted on the map.
- Download data is still a to-do.
- Should probably set up a github pages site and deployment workflow to host the app?
- Need to revisit and investigate api bandwidth usage to make sure we're not destroying users' cell data. Map data being compressed enough? Only load data on demand? I guess the biggest data is the full geojson data, so for example I could just load tracts when the user first selects it. Everything else is small (measures definitions) or loaded on demand (feature values).
- Should set up Netlify PR previews I guess.

**Comment by falquaddoomi** [comment]
Regarding the terms, I took "Category", "Measure", and "Value" from the schema of the input dataset. In the input,  the "Category" (e.g. "Sociodemographics") is the name of a table, and a "Measure" is either a column of that table or, in the long versions of the tables, a value from the "measure" column (see below about wide vs. long). The term "Value" corresponds to the "value" column in the long tables, or the value of a specific cell in the wide tables. I assume it'd be less confusing to stick to those terms, as whoever's using the website will also encounter them in the raw data, but I'll leave the decision to your judgement.

(About wide vs. long: The input data comes as CSVs, one per category, in two formats, wide and long. In the wide versions, each row is a FIPS entity -- i.e., an ID for a county or tract -- and the remaining columns are values of various measures for that entity. The long tables just have three columns, "FIPS", "measure", and "value", and each combination of FIPS and measure gets a row. The long tables are more convenient to read in, so I used those, but the data is the same between the two.)

About bandwidth, with modest GZip compression the size of the counties and simplified tracts comes in around 

About downloading data, I took a look at the KY site and it appears to produce a CSV of the long version of the table for the currently selected Level, Category, and Measure. When the geographic level is "County" or "Tract", the table has the following columns:
- `GEOID`: the FIPS identifiers for the entitities in the currently-selected geographic level
- `County`: plain text name of county; in the case of tracts, this is the county to which the tract belongs
- `State`: plain text state, in our case it's always "Colorado"
- `measure`: plain text name of the measure (and yes, every column has the same repeated value)
- `value`: the value of the measure for the current FIPS

Unlike the KY site, we don't currently have a geographic level for "Area Development Districts" (in CO's case they're Economic Development Districts), but for completeness' sake downloading the data in that case produces a CSV with the columns `add` (the name of the district), `State`, `measure`, and `value`. 

About hosting, sure, we can put it on GH pages. The backend will need a VM, so if you prefer to host the frontend on the same VM, that's very doable. No opinion on Netlify, but I suppose if we do add it we might as well host the frontend on GH pages, as the backend will need to be configured to allow frontend requests from a different origin.

About the bandwidth usage, after adding modest gzip compression to backend, the county and (simplified) tract geometry comes in at 2.1MB apiece. IMHO, 5.2MB on loading the site isn't too huge to load upfront, but if we add back in the high-resolution tracts we might consider fetching them only when the user asks for them.

**Comment by falquaddoomi** [comment]
> But looking at the cancerinfocus zip file, it has all the catchment areas in the country?
Right, cancerinfocus.org maintains data for a bunch of regions, including every US state. People could theoretically put whatever data they want in the database as long as it obeys the schema, but IMHO we should design around people using the cancerinfocus.org data. I'm also building the data importing pipeline that'll run each month with the assumption that that's where the data is coming from.

Regarding the structure that you linked, what do you mean by making it more consistent at each level? Maybe we can have a meeting to discuss this, as I imagine it could get very long in this thread...

**Comment by vincerubinetti** [comment]
Ah okay I thought cancerinfocus.org was attempting to do it for all the US but wasn't quite complete. Sounds good to keep with that.

**Comment by falquaddoomi** [comment]
FYI, I added some environment variables that were causing warnings for me when building the site, e.g. `VITE_URL`, `VITE_NAME`. Did you have another mechanism for supplying those values that you'd prefer for me to use?

About the API changes, would you prefer I make them on this PR, or do you prefer a new one?

**Comment by falquaddoomi** [comment]
Aha, sounds good; I've added your `./frontend/.env` file as the source of environment vars for the frontend container, then, even though this is technically redundant with Vue's build process (since it also reads the `.env`, I believe). Just FYI, I typically exclude `.env` files since I often use them for secrets, but it's fine for the frontend to have one as long as there isn't anything sensitive in there.

About the API changes, I'll just make them in this PR, then, so that the frontend and backend will be consistent once it's merged.

**Comment by vincerubinetti** [comment]
Yeah I was thinking about putting those static variables somewhere else besides .env for that very reason. The main reason I stick with that is because vite can automatically inject those into index.html for metatags and such.

But if others are going to use this, and since we have secrets in the top level .env, it might be best to move away from that. Maybe we can have a root (above /frontend and /backend) .json that has static vars for the whole project? I'll have to do some vite workarounds to string-replace it into index.html and be able to import things outside of /src (for using the vars in code).

**Comment by falquaddoomi** [comment]
It's fine with me to have a `.env` file in the `frontend` folder, since as you mentioned it makes it easier for people to run just the frontend outside of the stack.

If we were to move to configuration out of `frontend`, I'd prefer for us to keep the `.env` format so we don't have to reinvent anything. We could for instance add a second file, perhaps `.env.public`, that we do check into source control that contains the `VITE_` variables which is then used as the environment file for the frontend container, but as you observed, people would have to run the full stack to have it set up properly, though. Up to you, really, but I think the way things are now is fine.

**Comment by falquaddoomi** [comment]
Ok, I've restructured the `/stats/measures` endpoint as you requested. I wasn't sure if that was just an example of how you wanted the responses changed or if that's the only place; if there are other endpoints that need changing, let me know.

About renaming all the subkeys "children", I'm inclined to keep the "categories" and "measures" subkeys named that way, even if it means a bit more work in the frontend, because I intend for people to also be able to use the API directly, and having the keys have semantically meaningful names makes it easier to understand it IMHO.

**Review by falquaddoomi — APPROVED** [review]

**Pull request merged**
